package com.kirak.model;

/**
 * Created by Kir on 11.06.2017.
 */
public enum AptType {

    ONE_SINGLE_BED_STANDARD,
    TWO_SINGLE_BEDS_STANDARD,
    TWO_SEP_BEDS_STANDARD,
    TWO_SINGLE_BEDS_IMPROVED,
    TWO_SEP_BEDS_IMPROVED,
    TWO_SEP_BADS_COMFORT,
    FAMILY_THREE_WITH_SEP,
    FAMILY_THREE_WITHOUT_SEP,
    FAMILY_FOUR_WITH_SEP,
    FAMILY_FOUR_WITHOUT_SEP,
    FAMILY_FIVE_WITH_SEP,
    FAMILY_FIVE_WITHOUT_SEP,
    FAMILY_SIX_WITH_SEP,
    FAMILY_SIX_WITHOUT_SEP,
    HOSTEL_FOUR,
    HOSTEL_FIVE,
    HOSTEL_SIX,
    HOSTEL_SEVEN,
    HOSTEL_EIGHT,
    HOSTEL_NINE,
    HOSTEL_TEN
}
